---
arch: x86_64
image: fedora/latest
packages:
  - opam
  - gcc
  - gcc-c++
  - hostname
  - awk
  - bubblewrap
  - make
  - patch
  - m4
  - autoconf
  - rsync
  - btrfs-progs
sources:
  - "git@git.sr.ht:~gary-kim/othrottle"
secrets:
  - "5de7ec36-b900-47ba-be3d-4303475f46c2"
tasks:
  - setup_ocaml: |
      # The opam switch install runs out of space in builds.sr.ht.
      # Install into a compressed btrfs mount.
      truncate -s 15G ~/opam.img
      mkfs.btrfs ~/opam.img
      mkdir -p ~/.opam
      sudo mount -o compress=zstd:1 ~/opam.img ~/.opam
      sudo chown build:build ~/.opam

      opam init --yes --bare
      opam switch create 5.2.0+ox --repos ox=git+https://github.com/oxcaml/opam-repository.git,default --yes
      eval $(opam env)
      cd othrottle
      opam install . --deps-only --yes --assume-depexts --locked
  - format_check: |
      cd othrottle
      eval $(opam env)
      opam exec -- dune build @fmt
  - build: |
      cd othrottle
      eval $(opam env)
      opam exec -- dune build @all
  - test: |
      cd othrottle
      eval $(opam env)
      opam exec -- dune runtest
